using CoachingCards.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoachingCards.Services
{
    public class MockDataStore : IDataStore<Card>
    {
        readonly List<Card> items;

        public MockDataStore()
        {
            items = new List<Card>()
            {
                new Card(1, "<h1>1. Přijmi, změň, opusť</h1>", "Potřebuješ se rozhodnout? Zkus si pomoct trojicí reakcí: přijmi, změň, opusť.<br>PŘIJMI situaci takovou, jaká je.<br>ZMĚŇ sebe, svůj přístup, svůj úhel pohledu, své myšlení.<br>OPUSŤ situaci, která pro tebe nemá jiné vhodné řešení.<br><br>Jakékoliv rozhodnutí se stane mnohem snazší a sebevědomější. Například: Zavádění novinky v práci. Nadávat na vedení ani na systém ti nepomůže. Buď: <br>1. novinku prostě přijmeš takovou, jaká je,<br>2. nebo změníš svůj přístup a z původní nevýhody pro sebe uděláš výhodu,<br>3. nebo je to pro tebe neakceptovatelné, tudíž odcházíš.", "<b>Akce:</b> <i>Použij na své aktuální dilema.<i>", true),
                new Card(2, "<h1>2. Užitečné vs. zajímavé</h1>", "Pro rychlou a k výsledku vedoucí komunikaci a pro efektivní uvažování rozlišuj užitečné od zajímavého a věnuj se jenom užitečnému. Užitečné je to, co vede k vytyčenému výsledku. Zajímavé je to, co cestu k výsledku prodlužuje.<br><br>Například: Marie kamarádce podrobně vypráví, jak si na kole zranila koleno (orientace na zajímavé). Ale když jde Marie k lékaři, tak mu sdělí: „Bolí mě koleno. Tady.“ (Orientace na užitečné).<br><br>Zefektivníš komunikaci i přemýšlení a ušetříš čas.<br>Například: Pracovní porady zkrátíš o 50 % až 75 % času, zaměříš se na výsledek, zbavíš se zdržovacích odboček atd.", "<b>Akce:</b> <i>Vyzkoušej jeden den vědomě rozlišovat užitečné od zajímavého a dál se věnuj pouze užitečnému.<i>", true),
                new Card(3, "<h1>3. Sféry vlivu</h1>", "Ovlivňuj to, co ovlivnit můžeš. To je to, co tvoříš. To jsi ty.<br><br>Neztrácej energii tím, co ovlivnit nemůžeš.<br><br>A hlavně se soustřeď na to, abys dokázal tyto dvě kategorie rozlišit.<br><br><b>Například:</b> Svého šéfa, politika, rodiče ovlivnit nemůžeš. Můžeš ale ovlivnit svůj postoj k nim, svůj úhel pohledu.", "<b>Akce:</b> <i>Jeden den veškeré situace kolem sebe posuzuj, zda jsou přímo tebou ovlivnitelné, či nikoliv. Věnuj se jen těm, které můžeš přímo ovlivnit. Všimni si množství ušetřené energie a času.<i>", true),
                new Card(4, "<h1>4. Tady a teď se zdroji, které máš</h1>", "Uvědom si, že vše, co v životě činíš, děláš nejlépe, jak umíš. Tady a teď se zdroji, které máš. Věř v sebe, ve své schopnosti a nereviduj svá minulá rozhodnutí.<br><br>Jakýkoliv pohled zpět je vždy „po bitvě generálem“. Pouč se z historie.", "<b>Akce:</b> <i>Vezmi jedno své životní rozhodnutí typu: jak by se odehrával můj život, kdyby to tehdy bylo jinak. Tentokrát si ale věcně a konkrétně uvědom, jaké tehdy byly tvé zdroje (což jsou i informace), a ruku na srdce, jaké by bylo tvé rozhodnutí znovu za stejných okolností?<i>", true),
                new Card(5, "<h1>5. Vidíme mozkem</h1>", "Očima ve skutečnosti nevidíme. Na svět se díváme mozkem.<br><br>Vše, co k nám přichází, projde skrz síto našich myšlenek, zkušeností a návyků. Klasickým příkladem je sklenice, která může být pro jednoho poloplná a pro jiného poloprázdná.", "<b>Akce:</b> <i>Podebatuj s někým o svých prioritách, bez kterých se nedá žít.<i>", true),
                new Card(6, "<h1>6. Fáze učení mozku:</h1>", "Proces osvojování si nového návyku má čtyři fáze:<br>1.nevědomá a nezkušená<br> – starý zvyk / automatismus<br>2. vědomá, nezkušená<br> – získá se po prvních 21 opakováních<br>3. vědomá, zkušená<br> – získá se po dalších 1 000 opakováních (fáze 1 021 opakování zabere přibližně 90 dnů)<br>4.nevědomá, zkušená<br> – nový návyk / automatismus", "<b>Akce:</b> <i>Když se ti něco hned nepovede, nenadávej si za to. Naopak si polož ruku na rameno a řekni si: „Žádný učený z nebe nespadl. Vytvářím nový návyk.“ A původní „To jsem ale de..l.“ nahraď „Někdy se to prostě nepovede, a co?“.<i>", true),
                new Card(7, "<h1>7. Každý mozek je jiný</h1>", "Každé vnímání světa je jiné.<br><br>Nikdo nemá tvé zkušenosti, tvé zvyky, tvé myšlenky, tvé zdroje. Nikdo ti nerozumí tak dokonale jako ty. Jsi jediný odborník na svůj život.<br><br>Řešení všech svých dilemat znáš. Jen je vytáhnout z hlubin mysli na světlo.", "<b>Akce:</b> <i>Podívej se, v kolika zásadních otázkách se společnost dělí do různých názorových skupin.Najdeš jedno téma, v němž jsou všichni zajedno?<i>", true),
                new Card(8, "<h1>8. Zvyk je železná košile</h1>", "I když je těžká, svléknout se dá.<br><br>Je dobré mít někoho, kdo ti pomůže „sundat“ starý nežádoucí zvyk a pomůže ti „obléct“ nový žádoucí návyk, který ukotvíš ve svém životě.", "<b>Akce:</b> <i>Vypiš si(zlo)zvyky, kterých se chceš zbavit. Napiš si také návyky, které by stály za osvojení. Co všechno díky nim získáš?<i>", true),
                new Card(9, "<h1>9. Prioritizace</h1>", "Prioritizuj podle míry důležitosti pro sebe.<br><br>Je - li to, čeho chceš dosáhnout, pro tebe v danou chvíli opravdu důležité, dej tomu absolutní prioritu. Mozek snáze pochopí, že to myslíš vážně.<br><br><b>Například:</b> Mám v úterý odpoledne sezení s koučem a do toho mi zavolá kamarád s nabídkou badmintonu. Svým výběrem dávám mozku jasně najevo, co je pro mě v danou chvíli důležité. Opakovanou volbou toto pochopitelně podpořím.", "<b>Akce:</b> <i>Co je tvou jasnou prioritou, která je nadřazená vždy a všemu? Co by mělo být tvou prioritou, a není?<i>", true),
                new Card(10, "<h1>10. Nevyžádané rady – informační dieta</h1>", "Nesmírně osvěžující informační dieta působí blahodárně na všech úrovních žití. Dopřej si pauzu od médií, sociálních sítí, telefonátů, reklam, schůzek. Buď jen ty, bez tlaku na to, co máš a nemáš dělat apod.<br>Po takové informační dietě určitě pocítíš lehkost a svěžest.Tohle má pro tebe ještě jeden efekt.Naučíš se efektivněji žádat o radu, když to skutečně budeš potřebovat.", "<b>Akce:</b> <i>Jeden den přistupuj ke všem informacím, které na tebe automaticky míří, a nejsou tebou výslovně vyžádány(TV, rádio, podcasty, články, zpravodajství, sociální sítě atd.), jako k nevyžádaným radám a odmítni je, nekompromisně, slušně a důsledně.Nevyžádané rady se od tebe budou odrážet jako od zrcadla. Bude to pro tebe nesmírně osvobozující a očistný proces.<i>", true),
                new Card(11, "<h1>11. Inventura úspěchů</h1>", "Naše přání bereme jako nedosažitelný sen do chvíle, než si ho splníme. Pak již bagatelizujeme jeho náročnost. I to, kolik úsilí nás stála realizace. Rychle zapomínáme na trnitou cestu, která nás mnohé naučila. Místo toho, abychom se z ní dlouhodobě poučili, říkáme „tak strašné/ náročné to zase nebylo“.", "<b>Akce:</b> <i>Vypiš si své dosavadní úspěchy.Co považuješ za své životní úspěchy? Jaké konkrétní úsilí tě jejich dosažení stálo? Jaké zlomové okamžiky tě na cestě za nimi čekaly?<i>", true),
                new Card(12, "<h1>12. Opuštění komfortní zóny</h1>", "Dělat věci nově, jinak, neobvykle.<br><b>Například:</b> Zvolit jinou cestu do práce, vystoupit třeba o stanici dříve a zbytek dojít pěšky. Dát si ráno studenou sprchu. Nakoupit v jiném obchodě než obvykle. K obědu si dát něco dosud neochutnaného. Po příchodu z práce udělat doma jako první něco úplně jiného než obyčejně. Dát si výzvu týdne a splnit ji. Zkrátka udělej cokoliv, co vybočuje z tvého běžného chování. Otestuj své vlastní hranice, dogmata a tabu.", "<b>Akce:</b> <i>Na nějaký čas přestaň dělat nějakou věc, která je pro tebe pohodlná, nebo naopak udělej něco jinak, nově.Pro začátek postačí i drobné změny v zažitých denních rituálech. Zapiš si nebo sdílej, co „šíleného“ se ti povedlo udělat, jak to na tebe zapůsobilo a své pocity při tom a potom.<i>", true),
                new Card(13, "<h1>13. Přání v posledním týdnu života</h1>", "Také máš na všechno hromadu času? Vždyť to ještě vydrží nebo udělám to zítra, za týden, po dovolené. Není na co čekat na kdy odkládat.Nikdy nevíme, kolik nám ještě zbývá času.", "<b>Akce:</b> <i>Napiš na papír svá přání, která si chceš splnit, kdyby ti zbýval poslední týden života.Text nech pár dnů uležet a pak se k němu vrať.Vrať se k němu ještě jednou za několik týdnů.Velké překvapení tě nemine.<i>", true),
                new Card(14, "<h1>14. Ne předponě ne</h1>", "Povšimni si, jak často začínají naše věty záporem. „Nepůjdeš ven?“ „Nemáš čas?“ „Nehodilo by se ti to?“ „Nedáš si něco dobrého na zub?“<br><br>Co tak toho „NE“ trochu ubrat? Nejde v žádném případě o to, vyhnat slovo „ne“ ze svého života. To určitě ne.Ne je potřebné, stejně jako ano, když ho použiješ v pravý čas. Jde o zmírnění záporného postoje ke každodenním činnostem, který tak často vyjadřujeme větami uvozenými právě negací.", "<b>Akce:</b> <i>Neustále, vždy a všude, v práci i doma zkoušej odstraňovat negaci ze slovníku i myšlení.Soustřeď se a vědomě se opravuj.<i>", true),
                new Card(15, "<h1>15. Pochvala vs. ocenění</h1>", "Pravé ocenění je na rozdíl od neurčité pochvaly konkrétní. Takže vím přesně, za co druhého oceňuji. Mělo by být upřímné, tedy věřím tomu, co říkám. Ocenění klade důraz na úsilí toho, kdo je oceňován. Ocenění si všímá právě samotné tvorby, změny a vynaložené práce. Při oceňování upozadíme své ego, zásadně nehodnotíme. Ano, může se nám práce druhého líbit, ale ocenění je co nejobjektivnější, takže vlastní hodnotící soud potlačíme.<br><br><b>Například:</b> Malý chlapec v lese postavil domeček pro skřítky. Nekonkrétní pochvala: „Ty jsi ale šikovný chlapeček.“ Konkrétní ocenění: „To ti muselo dát hodně práce. A kde jsi sehnal tu zelenou šišku? Vždyť tady jsou jen hnědé.“ Naučíš-li se oceňovat druhé, dokážeš pak ocenit i sebe. A neboj se, není to domýšlivost. Oceňuješ přece konkrétní práci a ta si to zaslouží.", "<b>Akce:</b> <i>Zkus jeden den místo nekonkrétní chvály a subjektivního hodnocení druhé oceňovat.<i>", true),
                new Card(16, "<h1>16. Naše limity a hranice</h1>", "Veškeré naše jednání ovlivňují zažité vzorce chování, které současně vytváří hranice našeho myšlení a konání. Tyto limity se v nás vytváří od prenatálu. Neustále. Jsme doslova bombardováni zažitými omezujícími vzorci chování. A to prostřednictvím svých nejbližších, našeho okolí, členů sociálních skupin, do nichž patříme. Přitom tyto limity jsou jen uměle vytvořené hranice.", "<b>Akce:</b> <i>Vyber si nějaký limit, který tě denně obtěžuje, a poznamenej si ho. Pod něj si napiš, co ti přináší a v čem ti brání.Nad sloupec, co ti přináší, napiš znaménko „−“ a nad sloupec, v čem ti brání, napiš znaménko „+“. Ano, je to správně.Protože omezující limit ti přináší do života nepohodlí a nesoulad, kdežto to, v čem ti brání, je většinou právě to, co si přeješ, co chceš.<i>", true),
                new Card(17, "<h1>17. Čas navíc</h1>", "Jednoduchý způsob, jak nesklouznout do nežádoucího automatismu.<br><br>Hluboký nádech.<br><br>Když jsou tvé emoce rychlejší než nádech, sklouzneš do automatismu. Nádech ti dá potřebný čas, aby se tak nestalo.", "<b>Akce:</b> <i>Zkoušej nádech při náhlém návalu emocí.<i>", true),
                new Card(18, "<h1>18. Vesmírná objednávka</h1>", "Udělej si konkrétní vesmírnou objednávku a celý vesmír se spojí, aby se tvé přání splnilo.", "<b>Akce:</b> <i>Napiš si vesmírnou objednávku. Buď konkrétní. Objednej si, co opravdu chceš, kolik toho má být a kdy ti to mají přivézt.<i>", true),
                new Card(19, "<h1>19. Do roka a do dne</h1>", "Co se ti má splnit do roka a do dne?", "<b>Akce:</b> <i>Co chceš jinak? Kterými konkrétními chytrými kroky k tomu dojdeš?<i>", true),
                new Card(20, "<h1>20. Chytré kroky</h1>", "Všechno, co máš, je výsledkem tvých dlouhodobých CHYTRÝCH kroků.", "<b>Akce:</b> <i>Podívej se na svůj jakýkoliv úspěch. Není podstatné, jak moc je pro tebe významný. Projdi si své jednotlivé CHYTRÉ kroky, které k němu vedly.<i>", true),
                new Card(21, "<h1>21. Porovnávání</h1>", "Jabloň, nebo smrk? Kdo je lepší? Jabloň se směje smrku: vždyť ani nemáš sladké plody, jsi k ničemu. Smrk se směje jabloni: v zimě jsi nahá, nemáš ani šišku, dokonce ani nevoníš. Každý je jiný.Každý máme vlastní důvod ke své existenci.Porovnáváním přímo do „pekla“.", "<b>Akce:</b> <i>Pohlídej si porovnávání.Zejména u dětí - sourozenců je to hned po ruce.Děti jsou osobnosti, stejně jako my dospělí. Také je každé jiné.<i>", true),
                new Card(22, "<h1>22. Rozděl se a nesuď</h1>", "Dej a bude ti dáno. Přej a bude ti přáno. Rozděl se o to, čeho máš málo. Ale nic za to nečekej. Dovol druhým, ať jsou sví, dovol jim dělat chyby. Dovol si je nesoudit.", "<b>Akce:</b> <i>Všímej si chyb druhých, ale nesuď je a neodsuzuj. Nemáš všechny zdroje(informace, zkušenosti, vstupy) druhých.<i>", true),
                new Card(23, "<h1>23. Uvolnění prostoru</h1>", "Pro lepší a klidnější přemýšlení, když se potřebuješ soustředit na své myšlenky(před jednáním, před zkouškou apod.), se hodí tzv. uvolnění prostoru.", "<b>Akce:</b> <i>Promítni si v hlavě situaci(bez podrobností!), zápornou, ale i pozitivní, která tě v daný okamžik nejvíce ovlivňuje(např.ranní srážka s blbcem, hádka s partnerem, sekec od šéfa nebo to, že se šíleně těšíš domů, protože jdeš se svou láskou do vaší oblíbené restaurace na večeři nebo tě čeká tvůj oblíbený sport). Uvědom si prosím, jaká to je emoce, pojmenuj ji jedním slovem a zjisti, kde na těle ji cítíš.Potom tuto emoci i s pomocí gesta odlož(kladnou si pak nezapomeň vzít zpět).<i>", false),
                new Card(24, "<h1>24. Podporování</h1>", "Jak by vypadal tvůj život, kdyby tě tví nejbližší podporovali, věřili v tebe, ve tvé schopnosti? Kdyby ti fandili? Naruš začarovaný kruh zajetých kolejí neposkytování podpory v životních snech. Ty můžeš podporovat, věřit a fandit svým dětem, blízkým, přátelům a nezapomeň i na sebe.", "<b>Akce:</b> <i>Podporuj své blízké.Potřebují to. Navíc se ti tato energie bohatě vrátí.Podporujte se navzájem.Klidně začněte malými věcmi.<i>", false),
                new Card(25, "<h1>25. Myslet jako bohatý</h1>", "Žít s pocitem „MÁM NA TO“ nebo „bohužel, to si nemohu dovolit“.<br><br>Žít s pocitem „MÁM NA TO“ je základem myšlení bohatého.", "<b>Akce:</b> <i>Dej si do peněženky 3 tisíce. Líbí se ti věc za 2 590 Kč.Stačí jít do obchodu, víš, že na to máš. Ovšem nekupuj ji.Důležité je, že MŮŽEŠ.<i>", false),
                new Card(26, "<h1>26. Kde je pozornost, je energie</h1>", "Princip se zaměřením pozornosti funguje vždy, všude a na vše.<br><b>Například:</b> Nesu několik krabic, hrozí, že spadnou. Zaměřím pozornost na to, že mohou spadnout. Co myslíš, že se stane? Ano, spadnou.Je mi zima na ruce.Zaměřím na ně pozornost s tím, že je mi teplo.Ruce se skutečně zahřejí.", "<b>Akce:</b> <i>Tři dlaně o sebe, až v nich pocítíš horko. Dej je pár centimetrů od sebe. Představ si, že v dlaních držíš kouli o velikosti grepu, a koulej ji.Potom přibližuj dlaně pomalinku k sobě, jako bys kouli stlačoval.Pocítíš jemný odpor energie.<i>", false),
                new Card(27, "<h1>27. Klíčem k mozku jsou emoce</h1>", "Emoce nám sdělují, v jakém souladu jsme sami se sebou. Zjednodušeně řečeno, emoce jsou kontrolním panelem, na kterém je škála od „je to hodně zlé“ přes „nejsem OK“ až po „jsem OK“ a „je to super“.<br><br>I sebelogičtější mozek se nakonec rozhoduje na základě emocí. Následnou analýzou pak většinou pouze zdůvodňujeme svá dřívější emocionální rozhodnutí.", "<b>Akce:</b> <i>Všímej si svých rozhodnutí a poctivě si přiznej, co i po důkladné úvaze nakonec převážilo jazýček vah.<i>", false),
                new Card(28, "<h1>28. Pocity nelžou</h1>", "Pocity nikdy nelžou, myšlenky mohou.<br><br><b>Například:</b> Že se mnou někdo manipuluje, poznám mnohem rychleji pocitově – necítím se v tom dobře. Rozumem manipulaci odhalím většinou až ex post, což může být pozdě.", "<b>Akce:</b> <i>Kdy se tvůj pocit osvědčil?<i>", false),
                new Card(29, "<h1>29. Vision board</h1>", "Vision board neboli nástěnka snů je velkým pomocníkem pro zaměření se na svá přání. Sny se stávají cíli a ještě více se přiblíží.", "<b>Akce:</b> <i>Vytvoř si vision board se vším, čeho chceš dosáhnout například v následujícím roce. Vyfoť si ho a dej si ho jako tapetu do mobilu. Síla vizualizace se zmnohonásobí.<i>", false),
                new Card(30, "<h1>30. Nálady jsou mé</h1>", "Mé nálady jsou mé a nikoho jiného. Vyvěrají z mého nitra a to je také mé. Jakýkoliv vnější stimul je vždy poměřován mou optikou se všemi mými zkušenostmi, prožitky, vzorci chování, teprve pak jej vnímám. Jak s vnějším podnětem naložím, je jen na mém uvážení, nikdo jiný to za mě neudělá. Svět je takový, jaký ho vnímám. Nemůže být ničím víc ani míň. Jen já ho můžu vnímat tak či onak. A pak bude takový či onaký.", "<b>Akce:</b> <i>Říkej si každý den několikrát jako mantru: „Mé nálady jsou mé a nikoho jiného. Jak naložím s vnějšími podněty, je jen na mně.“ Čiň tak, dokud si to dokonale nezvědomíš.<i>", false),
                new Card(31, "<h1>31. Velký úspěch</h1>", "", "<b>Akce:</b> <i>Vzpomeň si na svůj velký úspěch. Byla to paráda, co? Tento vítězný pocit si vědomě „nakopíruj“ do každé další budoucí akce.<i>", false),
                new Card(32, "<h1>32. Strach ze selhání</h1>", "Proč je v nás strach ze selhání tak hluboce zakořeněn? Protože v minulosti selhání znamenalo smrt. Mozek bohužel neumí intenzitu selhání vyhodnotit. Vyplatí se proto použít staré osvědčené: Zastav se a napočítej do deseti. První nával paniky odezní a přiměješ tak mozek přemýšlet.", "<b>Akce:</b> <i>Dej mozku čas, aby při chybě zjistil, že opravdu, ale opravdu nejde o život.<i>", false),
                new Card(33, "<h1>33. Strach v životě</h1>", "Strach v životě je jako sůl v polévce. Neosolená ani přesolená polévka se nedá jíst.", "<b>Akce:</b> <i>Pojmenuj jeden svůj strach. Představ si ho jako nějakou bytost, například pohádkovou, a nakresli ji. Už teď je strach poloviční. Bubák vytažený zpod postele na světlo není moc děsivý, co?<i>", false),
                new Card(34, "<h1>34. Změna znaménka</h1>", "Veškeré energii, která k tobě přichází, určuješ znaménko ty. Křičíš na mě? Děkuji ti, věnuješ mi pozornost, a tedy i energii.", "<b>Akce:</b> <i>Začni nejprve něčím snadným. Například televizními zprávami nebo rozhovorem o ničem s nějakým věčným pesimistou či prudičem. Nastav si vědomě, že veškerá energie, která k tobě proudí, je ti prospěšná, užitečná. Pak měň polaritu energie k tobě vysílané po částech (například po jednotlivých myšlenkách, větách). Z minus udělej plus. Usmívej se, to pomáhá. Změnu znaménka trénuj kdekoliv a kdykoliv. Klidně to doprovázej i slovy, gesty, čímkoliv, co ti pomůže si tuto techniku zafixovat.<i>", false),
                new Card(35, "<h1>35. Tvá vášeň</h1>", "Ve vášni se spojují a projevují tvé silné stránky. Na tom se dá stavět. Vyplatí se věnovat pozornost vlastní vášni.", "<b>Akce:</b> <i>Definuj svou vášeň. O čem dokážeš mluvit hodiny a hodiny s plamínky v očích? Co ti tvá vášeň může všechno dát? Jak ti může změnit život? Definuj konkrétně a v bodech.<i>", false),
                new Card(36, "<h1>36. Konflikt</h1>", "Konflikt je jen jiný úhel pohledu.", "<b>Akce:</b> <i>Při hrozícím konfliktu se podívej na řešené téma myšlenkami druhého diskutujícího. Půjč si na chvíli co nejvíce jeho zdrojů (informace, zkušenosti, záměr). Pomůže ti to alespoň z části pochopit jeho jednání a ve většině případů konflikt zažehnat ještě před jeho vypuknutím.<i>", false),
                new Card(37, "<h1>37. Mladý a starý duch</h1>", "Duchem mladý člověk zvrátí cokoliv. Duchem starý strčí hlavu do písku a nechá si nakopat zadek.", "<b>Akce:</b> <i>Dělej to, co tě omlazuje.<i>", false),
                new Card(38, "<h1>38. Není pozdě</h1>", "Čím odlišíš dnešní den od včerejšího a zítřejšího? Nikdy není pozdě na vyzkoušení něčeho nového.", "<b>Akce:</b> <i>Každý den udělej nebo se nauč něco nového.<i>", false),
                new Card(39, "<h1>39. Lhaní do kapsy</h1>", "Když si lžeš do kapsy, počítej s tím, že každá kapsa má omezenou nosnost. A lež dokáže být někdy pěkně těžká.", "<b>Akce:</b> <i>Řekni si pár rčení o lži a pravdě. Zamysli se nad jejich skutečným sdělením. Nejsou to taková klišé, jak to na první pohled může vypadat, že?<i>", false),
                new Card(40, "<h1>40. Nepružnost vůči změnám</h1>", "Nepružnost vůči změnám nás činí náchylnějšími vůči strachům. Změna je výzva, ne protivník.", "<b>Akce:</b> <i>Protahuj své tělo. Je prokázáno, že v zatuhlém těle těžko hledat flexibilního ducha.<i>", false),
                new Card(41, "<h1>41. Jedinečnost</h1>", "Jedinečnost není o tom, být nej. Tvá jedinečnost je tvá originalita, kterou druzí hledají. Pěstuj a hýčkej svou odlišnost (podivnost).", "<b>Akce:</b> <i>V čem spočívá tvoje jedinečnost? Co je tvé, co je ti opravdu vlastní? Co je tvoje „podivínství“?<i>", false),
                new Card(42, "<h1>42. Láska, víra, naděje</h1>", "LÁSKA je základní báze života.<br><br>VÍRA je mocná hybná síla.<br><br>NADĚJE je kompas cesty, která tě dovede.", "<b>Akce:</b> <i>Dovol si být láskou, cítit lásku, dávat lásku, přijímat lásku. Temenem hlavy nadechuj vesmírnou moudrost. Srdcem vydechuj světelný proud lásky.<i>", false),
                new Card(43, "<h1>43. Světlo</h1>", "Světlo jsi a ve světlo se obrátíš. Opravdu se potřebuješ zatemnit?", "<b>Akce:</b> <i>Zapal si svíčku. Koukej se do plamene. Myšlenky si představ jako suché podzimní listí, nechej je shořet v plamenu svíčky. Nad plamenem si zahřej dlaně a tímto očistným teplem si omyj obličej a hlavu.<i>", false),
                new Card(44, "<h1>44. Křídla</h1>", "Ztracenou svobodu si vezmi zpět. Přímo teď ti na tvých zádech rostou křídla.", "<b>Akce:</b> <i>S každým nádechem a výdechem nabývají na své síle. Jsi volnost sama.<i>", false),
                new Card(45, "<h1>45. Partnerství pro život</h1>", "Hledáš lásku, se kterou zestárneš? Co takhle najít lásku, se kterou nestárneš, ale naopak mládneš? Buďte oba stále bláznivě zamilovaní!", "<b>Akce:</b> <i>Udělejte společně bláznivou věc, o které ostatní říkají, že už se k vašemu věku nehodí. Třeba si postavte stan v obýváku.<i>", false),
                new Card(46, "<h1>46. Čas na změnu</h1>", "Nečekej na nic, využij toho, co máš teď. Udělej to, co chceš udělat už dlouho.<br>Přijmi ten dar dnešního dne a začni hned. Ne pak, ale teď! Dnes. Bez výmluv. Udělej to jinak, než doposud.", "<b>Akce:</b> <i>Co konkrétního můžeš udělat pro sebe dnes, aby se z toho dalo těžit zítra?<i>", false),
                new Card(47, "<h1>47. Vzestup a pád</h1>", "Máš pocit, že jsi na dně? Tak se ode dna odraz a stoupej výš, až nad počáteční bod tvého klesání.<br><b>Například:</b> Dítě, které se učí chodit, v průměru 2 000krát upadne. Jsou pro něj pády důvodem, aby se nenaučilo chodit?", "<b>Akce:</b> <i>Všechno zlé je pro něco dobré. Jakým způsobem tě posílil poslední pád?<i>", false),
                new Card(48, "<h1>48. Vůně</h1>", "Rozpomeň se.", "<b>Akce:</b> <i>Vybav si 3 vůně z dětství.<i>", false),
                new Card(49, "<h1>49. Jídla</h1>", "Rozpomeň se.", "<b>Akce:</b> <i>Vybav si tři jídla z dětství, která z tvého jídelníčku zmizela.<i>", false)
            };
        }

        public async Task<bool> AddItemAsync(Card item)
        {
            items.Add(item);

            return await Task.FromResult(true);
        }

        public async Task<bool> UpdateItemAsync(Card item)
        {
            var oldItem = items.Where((Card arg) => arg.ID == item.ID).FirstOrDefault();
            items.Remove(oldItem);
            items.Add(item);

            return await Task.FromResult(true);
        }

        public async Task<bool> DeleteItemAsync(int id)
        {
            var oldItem = items.Where((Card arg) => arg.ID == id).FirstOrDefault();
            items.Remove(oldItem);

            return await Task.FromResult(true);
        }

        public async Task<Card> GetItemAsync(int id)
        {
            return await Task.FromResult(items.FirstOrDefault(s => s.ID == id));
        }

        public async Task<IEnumerable<Card>> GetItemsAsync(bool forceRefresh = false)
        {
            return await Task.FromResult(items);
        }
    }
}